import rtconfig
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.

src = Glob('GD32F403_standard_peripheral/Source/*.c')
src += [cwd + '/CMSIS/GD/GD32F403/Source/system_gd32f403.c']

#add for startup script
if rtconfig.CROSS_TOOL == 'gcc':
    src += [cwd + '/CMSIS/GD/GD32F403/Source/GCC/startup_gd32f403.S']
elif rtconfig.CROSS_TOOL == 'keil':
    src += [cwd + '/CMSIS/GD/GD32F403/Source/ARM/startup_gd32f403.s']
elif rtconfig.CROSS_TOOL == 'iar':
    src += [cwd + '/CMSIS/GD/GD32F403/Source/IAR/startup_gd32f403.s']

path = [
    cwd + '/CMSIS/GD/GD32F403/Include',
    cwd + '/CMSIS',
    cwd + '/GD32F403_standard_peripheral/Include',]
    
if GetDepend(['RT_USING_BSP_USB']):
    path += [cwd + '/GD32F403_usb_driver/Include']
    src  += [cwd + '/GD32F403_usb_driver/Source']

CPPDEFINES = ['USE_STDPERIPH_DRIVER', 'GD32F403']

group = DefineGroup('GD32_Lib', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
